name: example
description: sqlbrite example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.3
  path: ^1.8.0
  intl: ^0.17.0
  sqlbrite:
  flutter_lints: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sqlbrite:
    path: ../

flutter:
  uses-material-design: true
