name: example
description: sqlbrite example
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.11
  path: ^1.8.1
  intl: ^0.17.0
  sqlbrite:
  flutter_lints: ^2.0.1
  rxdart_ext: ^0.2.5
  collection: ^1.16.0
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sqlbrite:
    path: ../

flutter:
  uses-material-design: true
