name: example
description: sqlbrite example
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.19.0
  sqlbrite:
  flutter_lints: ^3.0.1
  rxdart_ext: ^0.2.9
  collection: ^1.17.2
  platform: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sqlbrite:
    path: ../

flutter:
  uses-material-design: true
