name: Build example

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ 'stable' ]
    defaults:
      run:
        working-directory: ./example
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2.13.0
        with:
          channel: ${{ matrix.channel }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format lib --set-exit-if-changed

      - name: Analyze
        run: flutter analyze lib

      - name: Build APK
        run: flutter build apk --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v3
        if: ${{ matrix.channel == 'stable' }}
        with:
          name: app
          path: example/build/app/outputs/apk/release/app-release.apk
